### PR TITLE
Bug 1209961 - change gaia_icons version

### PR DESCRIPTION
**Pull request by autra**

### CODE REVIEW

**Comment by wilsonpage** [comment]
You need to `bower install` locally and select a gaia-icons version to persist. Then push to Travis and this should run correctly :)

**Comment by autra** [comment]
Oh I see. I'll wait for https://github.com/gaia-components/gaia-icons/pull/51 to land anyway.

**Comment by autra** [comment]
I guess if I wait for gaia-header to land as well, I won't need to select the version manually :-)

**Comment by autra** [comment]
Closing, because I'm pretty sure we don't need this change anyway.

**Pull request closed without merging**
