### PR TITLE
Emit 'rendered' event when list is ready to be shown (closes #24)

### LINKED ISSUE #24: Fire a 'firstrender' event
If we tell the app when the list has rendered something, they can make the decision when to reveal the page to the user. This will be required if we are going to do any `<body hidden>` tricks to prevent Gecko wasting cycles rendering partially complete UI.

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
Depends on:
- https://github.com/gaia-components/fast-list/pull/89
- https://github.com/gaia-components/gaia-fast-list/pull/22

**Comment by wilsonpage** [comment]
@etiennesegonzac r?

**Comment by etiennesegonzac** [comment]
Needs rebase ;)

**Comment by wilsonpage** [comment]
Rebased and ready to land :green_heart:

**Comment by etiennesegonzac** [comment]
All good!

**Pull request merged**
